# Generated by Django 5.2.7 on 2025-12-21 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('BRIDAL', 'Bridal'), ('HAIR', 'Hair Care'), ('SKIN', 'Skin Care'), ('MAKEUP', 'Makeup'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in PKR', max_digits=10)),
                ('duration', models.PositiveIntegerField(help_text='Duration in minutes')),
                ('image', models.ImageField(blank=True, null=True, upload_to='packages/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Service Package',
                'verbose_name_plural': 'Service Packages',
            },
        ),
    ]
